# Generated by Django 4.2.4 on 2023-09-04 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(null=True, related_name='listingWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
