# Generated by Django 4.2.4 on 2023-09-06 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_bid_auction_bid_auction_auction_date_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['auction', 'date'], 'verbose_name': 'comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_end',
            field=models.DateField(verbose_name=datetime.date(2023, 9, 13)),
        ),
    ]
