# Generated by Django 4.2.4 on 2023-09-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comment_options_alter_auction_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_end',
            field=models.DateField(auto_now_add=True),
        ),
    ]
