# Generated by Django 4.2.4 on 2023-09-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_high_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='high_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auctions.bid'),
        ),
    ]
