# Generated by Django 4.2.4 on 2023-09-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='user',
        ),
        migrations.AddField(
            model_name='winner',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auctions.auction'),
        ),
    ]
