# Generated by Django 4.2.4 on 2023-09-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_winner_user_winner_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='auction',
        ),
    ]
