# Generated by Django 4.2.4 on 2023-09-07 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_winner_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ManyToManyField(blank=True, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='winner',
        ),
    ]
